---

db_hostname: "{{ hostvars[groups['db_server'][0]]['inventory_hostname'] }}"
scm_hostname: "{{ hostvars[groups['scm_server'][0]]['inventory_hostname'] }}"
edge_hostname: "{{ hostvars[groups['edge_servers'][0]]['inventory_hostname'] }}"

cluster_display_name: cluster_1

cdh_services:

  - type: hbase

  - type: hdfs
    dfs_data_dir_list: /dfs/dn
    fs_checkpoint_dir_list: /dfs/snn
    dfs_name_dir_list: /dfs/nn
    dfs_journalnode_edits_dir: /dfs/jn

  - type: hive

  - type: hue

  - type: impala
    scratch_dirs: /tmp/impala

  - type: oozie
  # Needed for CDH #

  # -type: sentry

  # Needed for CDH ( End ) #

  # Needed for CDP #
  - type: tez
 
  - type: hive_on_tez

  - type: solr

  - type: ranger

  - type: kafka
 
  - type: atlas

  # Needed for CDP ( End ) #
  - type: spark

  - type: yarn
    yarn_nodemanager_local_dirs: /tmp/nm
    yarn_nodemanager_log_dirs: /var/log/nm

  - type: zookeeper
