---

# 'ad', 'mit', or 'none' to disable security
krb5_kdc_type: mit

krb5_kdc_master_passwd: changeme

krb5_kdc_admin_user: "cloudera-scm/admin@{{ hostvars[groups['krb5_server'][0]]['default_realm'] }}"
krb5_kdc_admin_passwd: changeme

