---

- include: 36322.yml

- name: Install Cloudera Manager Agents
  yum: name={{ item }} state=installed
  with_items:
    - cloudera-manager-daemons
    - cloudera-manager-agent

- name: Configure Cloudera Manager Agent 'server_host'
  lineinfile: dest=/etc/cloudera-scm-agent/config.ini regexp=^server_host line=server_host={{ hostvars[scm_hostname]['inventory_hostname'] }}

- name: Restart Cloudera Manager Agents
  service: name=cloudera-scm-agent state=restarted enabled=yes
