---
  - name: install krb5
    yum:
       name:
         - krb5-libs
         - krb5-workstation
       state: present

  - name: copy krb5.conf
    template:
      src: krb5.conf.j2
      dest: /etc/krb5.conf
      mode: 0644
      owner: root
      group: root
      backup: yes
      force: yes
