---
  - name: Install packages
    yum:
       name:
         - adcli
         - samba-common
         - sssd
         - realmd
         - oddjob
         - oddjob-mkhomedir
         - samba-common-tools
         - python-pip
       state: present
      
  - name: Restart the messagebus service, otherwise the realmd service will not start
    command: systemctl restart messagebus

  - name: pexpect is required to handle pwd prompt
    pip: name=pexpect

  - name: Copy realmd.conf
    template: src=realmd.conf.j2 dest=/etc/realmd.conf mode=0644 owner=root group=root backup=yes force=yes

  - name: Restart the realmd service
    command: systemctl restart realmd

  - name: Join using realmd
    expect:
      command: /bin/bash -c "/usr/sbin/realm join {{ ad_domain }} -U {{ bind_user }} --membership-software=adcli --user-principal=host/{{inventory_hostname}}@{{krb5_realm}}"
      responses:
        Password for .*: "{{ bind_password }}"

  - name: Copy sssd.conf
    template: src=sssd.conf.j2 dest=/etc/sssd/sssd.conf mode=0600 owner=root group=root backup=yes force=yes

  - name: Restart the sssd service
    command: systemctl restart sssd

  - name: Copy nscd.conf
    template: src=nscd.conf.j2 dest=/etc/nscd.conf mode=0644 owner=root group=root backup=yes force=yes

  - name: Restart the nscd service
    command: systemctl restart nscd
