---

- name: Copy Java RPM file to temp directory
  copy: 
    src: "{{ java_rpm_location }}"
    dest: "{{ tmp_dir }}/jdk.rpm"
    remote_src: "{{ java_rpm_remote_src }}"
  when: java_installation_strategy == 'rpm'

- name: Install Java from RPM
  package:
    name:
    - "{{ tmp_dir }}/jdk.rpm"
    state: installed
  when: java_installation_strategy == 'rpm'

- name: Install Java from package repository
  package:
    name:
    - "{{ java_package }}"
    state: installed
    update_cache: yes
  when: java_installation_strategy == 'package'

- name: Add missing symlinks (if installed from Cloudera repo)
  block:
    - name: Find Java home directory
      find:
        paths: /usr/java
        patterns: 'jdk*-cloudera'
        file_type: directory
        recurse: no
      register: cloudera_jdk_home
    - name: Create alternatives symlink for java
      alternatives:
        name: java 
        link: /usr/bin/java
        path: "{{ cloudera_jdk_home.files[0].path}}/bin/java"
      when: cloudera_jdk_home.matched
    - name: Create default symlink for Java home directory
      file:
        src: "{{ cloudera_jdk_home.files[0].path}}" 
        dest: /usr/java/default
        state: link
      when: cloudera_jdk_home.matched
  when: java_installation_strategy != 'none'

- name: Capture installed Java provider
  raw: /usr/bin/java -version 2>&1 | egrep -o 'Java\(TM\)|OpenJDK' | sed 's/Java(TM)/Oracle/' | tr '[A-Z]' '[a-z]' | head -1
  register: provider
  when: java_installation_strategy != 'none'

- name: Capture installed Java version
  raw: /usr/bin/java -version 2>&1 | grep version | tr -d '"' | tr "_" " " | awk '{print $3"\n"$4}'
  register: version
  when: java_installation_strategy != 'none'

- set_fact:
    installed_jdk_provider: "{{ provider.stdout_lines[0] }}" 
    installed_jdk_version: "{{ version.stdout_lines[0] }}"
    installed_jdk_update: "{{ version.stdout_lines[1] }}"
  when: java_installation_strategy != 'none'

- name: Enable Unlimited Strength Policy (Oracle JDK7)
  include_tasks: install_jce_from_zip.yml
  vars: 
    java_home: /usr/java/default
    unarchived_directory: UnlimitedJCEPolicy
  when: java_installation_strategy != 'none' and installed_jdk_provider == 'oracle' and installed_jdk_version == '1.7.0'

- name: Enable Unlimited Strength Policy (Oracle JDK8 before u151)
  include_tasks: install_jce_from_zip.yml
  vars: 
    java_home: /usr/java/default
    unarchived_directory: UnlimitedJCEPolicyJDK8
  when: java_installation_strategy != 'none' and installed_jdk_provider == 'oracle' and installed_jdk_version == '1.8.0' and installed_jdk_update|int < 151

- name: Enable Unlimited Strength Policy (Oracle JDK8 after u151)
  include_tasks: install_jce_from_config.yml
  vars: 
    java_home: /usr/java/default
  when: java_installation_strategy != 'none' and installed_jdk_provider == 'oracle' and installed_jdk_version == '1.8.0' and installed_jdk_update|int >= 151

- name: Enable Unlimited Strength Policy (OpenJDK)
  include_tasks: install_jce_from_config.yml
  vars: 
    java_home: /usr/lib/jvm
  when: java_installation_strategy != 'none' and installed_jdk_provider == 'openjdk' and installed_jdk_version is not match("11.*")
